name: firmus
description: Firmus


version: 1.0.0+35

environment:
  sdk: '>=3.5.0-152 <4.1.0'



dependencies:
  firebase_messaging: 14.9.4
  firebase_dynamic_links: 5.5.7
  firebase_core: 2.32.0
  firebase_auth:
  firebase_crashlytics: ^3.5.7
  firebase_remote_config:
  upgrader: ^10.0.1
  flutter_web_plugins:
    sdk: flutter
  flutter_video_info:
  universal_platform:
  device_safety_info: ^0.0.2
  app_settings: ^5.1.1
  flutter:
    sdk: flutter
  fpdart: ^1.1.0
  visibility_detector:
  package_info_plus:
  camera: ^0.10.5+6
  lottie:
  async:

  rxdart:
  hive_flutter:
  chat_bubbles: ^1.5.0
  ffmpeg_kit_flutter_min_gpl:

  open_mail_app:
    git:
      url: https://github.com/bashar963/open-mail-app-flutter.git
  hive:
  flutter_expanded_tile: ^0.3.7
  flutter_map: ^6.0.0-dev.3
  latlong2:
  equatable:
  riverpod: ^3.0.0-dev.3
  hooks_riverpod:
  sticky_headers:
  dio_smart_retry:
  location:
  collection: ^1.17.0
  flutter_hooks:
  go_router: ^13.0.1
  freezed: ^2.3.2
  flutter_localizations:
    sdk: flutter
  intl:
  flutter_form_builder:
  form_builder_validators:
    git: https://github.com/gairick-saha/form_builder_validators.git
  flutter_svg: ^2.0.6
  fade_and_translate: ^0.1.3
  flutter_animate: ^4.1.1+1
  flutter_card_swiper: ^7.0.0
  percent_indicator: ^4.2.3
  cached_network_image: ^3.3.0
  share_plus: ^7.0.2
  focus_detector_v2: ^3.1.0+1

  uuid:
  cupertino_icons: ^1.0.2
  freezed_annotation: ^2.2.0
  custom_image_crop: ^0.0.5
  crop_your_image: ^0.7.5
  image_picker: ^1.0.4
  image_picker_for_web: ^3.0.3

  cloud_firestore:

  dio:
  localstore: ^1.3.5
  simple_logger: ^1.9.0+2
  video_player:
  video_editor: ^3.0.0
  path_provider:
  path:
  dotted_border: ^2.0.0+3
  flutter_image_compress: ^2.0.3
  custom_rating_bar: ^2.0.5
  video_compress: ^3.1.2
  permission_handler: ^11.0.1
  firebase_analytics:
  shimmer: ^3.0.0
  email_validator: ^2.1.17
  #  purchases_flutter:
  pausable_timer:
  flutter_markdown:
  font_awesome_flutter:
  expandable:
  flutter_riverpod: any
  markdown: any
  url_launcher: ^6.3.0
dev_dependencies:

  custom_lint:
  riverpod_lint:
  build_runner: ^2.3.3
  flutter_gen_runner:
  icons_launcher: ^2.1.3



  flutter_lints:

#  flutter_test: any
dependency_overrides:
  vm_service: ^14.0.0
icons_launcher:
  image_path: "assets/firmus_icon.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

flutter_gen:
  integrations:
    flutter_svg: true


flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/animations/
    - assets/images/nav/
    - assets/fonts/

  fonts:
    - family: SourceSansPro
      fonts:
        - asset: assets/fonts/SourceSansPro-ExtraLight.otf
          weight: 100
        - asset: assets/fonts/SourceSansPro-Light.otf
          weight: 200
        - asset: assets/fonts/SourceSansPro-Regular.otf
          weight: 400
        - asset: assets/fonts/SourceSansPro-Semibold.otf
          weight: 600
        - asset: assets/fonts/SourceSansPro-Bold.otf
          weight: 700
        - asset: assets/fonts/SourceSansPro-Black.otf
          weight: 900