// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDfKNTVYD0EbCN7SmgQDgfXqRtDA5I4to',
    appId: '1:749687638156:web:f13fe17430fab450e413a9',
    messagingSenderId: '749687638156',
    projectId: 'firmus-jobs',
    authDomain: 'firmus-jobs.firebaseapp.com',
    storageBucket: 'firmus-jobs.appspot.com',
    measurementId: 'G-MFDK9YFWG1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD6AET7LOelH3JMb2o8S85J2WXj3HCRciU',
    appId: '1:749687638156:android:22639510458a4328e413a9',
    messagingSenderId: '749687638156',
    projectId: 'firmus-jobs',
    storageBucket: 'firmus-jobs.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTV8vIETkRVhYxva9G8yMJZ_uD3r5OB1A',
    appId: '1:749687638156:ios:15f23b9f0d05bbeee413a9',
    messagingSenderId: '749687638156',
    projectId: 'firmus-jobs',
    storageBucket: 'firmus-jobs.appspot.com',
    iosClientId: '749687638156-a9a81ffcs9osqhh1q4qg5s32h6p3fub0.apps.googleusercontent.com',
    iosBundleId: 'com.firmusapp.jobs',
  );
}
